<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>WIE_Dashboard_NEW</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>AFLCMC.ico</ApplicationIcon>
    <AssemblyName>WIE Dashboard</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="AFLCMC.ico" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BouncyCastle.Crypto">
      <HintPath>..\..\..\BouncyCastle.Crypto.dll</HintPath>
    </Reference>
    <Reference Include="itextsharp">
      <HintPath>..\..\..\itextsharp.dll</HintPath>
    </Reference>
    <Reference Include="PdfSharp">
      <HintPath>..\..\..\PdfSharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>